### ISSUE TITLE
Azure app service - System.Runtime.InteropServices.SEHException / NativeLibraryLoader.FixDllNotFoundException

### ISSUE THREAD

**Issue by kurtgronbech** [imazen/imageflow-dotnet#3]
I'm getting the error below error when running in Azure app service. The code I'm using is the BlobFileHandler from the other [thread](https://github.com/imazen/imageflow-dotnet/issues/1) I created.

Project platform target: x64
Azure app service platform: 64-bit

Imageflow.NativeRuntime.win-x86_64-sandybridge (1.0.0-rc8) is referenced in project and I can see both these files in App service: 

d:\home\site\wwwroot\Imageflow.dll
d:\home\site\wwwroot\Imageflow.Net.dll

Any ideas? 

```
Application: kfweb.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32, UInt32)
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Func`1<IntPtr>, System.Collections.Generic.IEnumerable`1<System.String>)
   at Imageflow.Bindings.JobContextHandle..ctor()
   at Imageflow.Bindings.JobContext..ctor()
   at BlobFileHandler+<Invoke>d__2.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass4.<CreateCallbackVoid>b__3(System.IAsyncResult)
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageCommandAsyncResult.OnComplete()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndOperation[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.WindowsAzure.Storage.Core.Executor.ExecutionState`1<System.__Canon>)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1+<>c__DisplayClass1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<StartCopyStream>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by nathanaeljones** [comment]
That is very, very strange. That API should not be able to cause that kind of exception. Can you try running imageflow_tool.exe from the service and see if a similar error occurs?

**Comment by kurtgronbech** [comment]
I'll do some testing with imageflow_tool.exe this weekend.

**Comment by nathanaeljones** [comment]
I've added new APIs for executing imageflow_tool directly from the library.

**Comment by nathanaeljones** [comment]
Has this been resolved? I will reopen if not.

**Comment by kurtgronbech** [comment]
No it has not been resolved. I've been meaning to get back to this and will try to do some testing asap. Please reopen.

**Comment by jameskeongchen** [comment]
can we reopen this please?

I have a similar project on azure functions with an error from not finding the Imageflow.NativeRuntime.win-x86_64: I have this Nuget loaded in the project and the .net wrapper but im still gettting an issue with the NativeLibraryLoader - is there something simple i'm missing with the runtime library output configuration?

Error resizing Using "[basename].dll" Subdir="x64", IsUnix=False, IsDotNetCore=True
Before searching: Unable to load DLL 'imageflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
File not found: C:\Users\<username>\AppData\Local\Azure.Functions.V2.Cli\x64\imageflow.dll
File not found: C:\Users\<username>\AppData\Local\Azure.Functions.V2.Cli\imageflow.dll
File not found: C:\Users\<username>\source\repos\<projectname>\bin\Debug\netstandard2.0\bin\x64\imageflow.dll
File not found: C:\Users\<username>\source\repos\<projectname>\bin\Debug\netstandard2.0\bin\imageflow.dll
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflow_abi_ver_major, UInt32 imageflow_abi_ver_minor)
   at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0()
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
