### ISSUE TITLE
Apple Silicon M1 Pro: Unable to load shared library 'libdl.so'

### ISSUE THREAD

**Issue by pieterdhondt** [imazen/imageflow-dotnet#39]
Using code:

```c#
private async Task<string> GetThumbnailBase64(byte[] imageBytes)
{
       using (var b = new ImageJob())
        {
            var r = await b.Decode(imageBytes)
                .ResizerCommands("width=100&height=100&mode=crop")
                .EncodeToBytes(new MozJpegEncoder(50,true))
                .Finish().InProcessAsync();

            var base64thumbnail = r.First.TryGetBytes().HasValue ? Convert.ToBase64String(r.First.TryGetBytes().Value) : null;
            return base64thumbnail;
        }       
}
```

I am not able to use the library on a Mac with M1 Pro on macOS 12.0.1.
It throws the following exception:

```
System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibdl.so, 0x0001): tried: 'liblibdl.so' (no such file), '/usr/local/lib/liblibdl.so' (no such file), '/usr/lib/liblibdl.so' (no such file), '/Users/pieterdhondt/Git/topics-service/TopicsService.Api/liblibdl.so' (no such file), '/usr/local/lib/liblibdl.so' (no such file), '/usr/lib/liblibdl.so' (no such file)
         at Imageflow.Bindings.UnixLoadLibrary.dlopen(String fileName, Int32 flags)
         at Imageflow.Bindings.UnixLoadLibrary.Execute(String fileName)
         at Imageflow.Bindings.NativeLibraryLoader.LoadLibrary(String fullPath, IntPtr& handle, Nullable`1& errorCode)
         at Imageflow.Bindings.NativeLibraryLoader.TryLoadByBasenameInternal(String basename, ILibraryLoadLogger log, IntPtr& handle, IEnumerable`1 customSearchDirectories)
         at Imageflow.Bindings.NativeLibraryLoader.TryLoadByBasename(String basename, ILibraryLoadLogger log, IntPtr& handle, IEnumerable`1 customSearchDirectories)
         at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
         at Imageflow.Bindings.JobContextHandle..ctor()
         at Imageflow.Bindings.JobContext..ctor()
         at Imageflow.Fluent.ImageJob.FinishAsync(JobExecutionOptions executionOptions, SecurityOptions securityOptions, CancellationToken cancellationToken)
```
The same code runs fine on Windows or within a Linux container.

Any advice?

**Comment by shane9** [comment]
```cs
internal static class UnixLoadLibrary
{
        // TODO: unsure if this works on Mac OS X; it might be libc instead
        [DllImport("libc.dylib", SetLastError = true, CharSet = CharSet.Ansi)]
        private static extern IntPtr dlopen(string fileName, int flags);
        ...
}
```

Changing libdl.so to libc.dylib fixes this issue. Then there will be an issue loading libimageflow. Haven't looked into that yet.

**Comment by lilith** [comment]
What version of .NET are you using? We try to support everything .NET Standard 2.0 does, which means a lot of hackery for every runtime and platform.

**Comment by shane9** [comment]
.NET 6.0 on M1 Mac

**Comment by heinzmuller** [comment]
Same issue here, any suggestions @shane9 @pieterdhondt? :)

**Comment by adamshaylor** [comment]
.NET 6.0.400 on M1 for me.

**Comment by lilith** [comment]
I don't have a M1 mac to add support for aarch64 / mac... I bought a 2020
retina prior to the announcement.

**Comment by lilith** [comment]
Duplicate of https://github.com/imazen/imageflow/issues/592

**Comment by piotr-szczygiel** [comment]
Hi, I have same issue (net7, M2). 
Any news about when it will be fixed? It's nearly 2 years since when it was originaly reported.

**Comment by lilith** [comment]
Apple Silicon isn't supported yet except in x86 emulation mode; I don't
have an M1/M2 to test with and there don't seem to be many people using it.
Is your company interested in funding it?

**Comment by EzzeldenElshrbaty** [comment]
Hi, I have the same issue (net7, M2). any updates????

**Comment by lilith** [comment]
So far nobody has volunteered to work on it or loan me the hardware I would
need to test and port it to Apple Silicon.

**Comment by EzzeldenElshrbaty** [comment]
I think it will be a little hard because most of the developers are in different countries.

**Comment by lilith** [comment]
We support osx-arm64, if nuget update doesn't work, add https://www.nuget.org/packages/Imageflow.NativeRuntime.osx-arm64/ directly.
